### ISSUE TITLE
Prod error for s3 bucket upload evidence

### ISSUE THREAD

**Issue by ayshu2001** [bahrain-bp/bqa-genai-challenge#134]
The code works in local host. but the 3 lines commented out in Pre-defined Templates page, if uncommented makes all the pages go blank with error about constructor 't' undefined.

**Comment by ayshu2001** [comment]
@cerashdan I have created a new issue for the error that we discussed. 
The following lines of code if uncommented from the PreDefinedTemplates.tsx page makes everything go blank and shows no errors at all except for the constructor 't' undefined.
// import * as AWS from 'aws-sdk';
// const s3 = new AWS.S3();
// const uploadResult = await s3.upload(params).promise();

it works fine in my stage but only in main, it doesn't work.

**Comment by maalsaegh** [comment]
As discussed, use this reference https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/s3-example-photo-album.html#s3-example-photo-album-adding-photos to update the code

**Comment by ayshu2001** [comment]
index-5765315c.js:1547 Uncaught TypeError: t is not a constructor
    at m_ (index-5765315c.js:1547:24633)
    at he (index-5765315c.js:1561:797)
    at index-5765315c.js:1537:83614

this is the error showing only


![Image](https://github.com/bahrain-bp/bqa-genai-challenge/assets/120376345/c4132a6a-c8d3-4fb9-b15c-0870975a71fc)

**Comment by ayshu2001** [comment]
instead of import AWS form aws-sdk, I used aws-sdk as below: 


![Image](https://github.com/bahrain-bp/bqa-genai-challenge/assets/120376345/7b7051c0-29b1-49e0-b581-2ea30c3fc721)
